### ISSUE TITLE
Update repo topics

### ISSUE THREAD

**Issue by hauten** [XBraid/xbraid#24]
A new page on the LLNL software portal (https://software.llnl.gov/radiuss/) will soon dynamically pull in RADIUSS repos. To achieve this, we need RADIUSS-related repos outside the LLNL org to be tagged with relevant topics. See https://github.com/LLNL/llnl.github.io/issues/17, https://github.com/LLNL/llnl.github.io/issues/151, & https://github.com/LLNL/llnl.github.io/blob/new-home-page/radiuss/README.md for additional context.

For XBraid, please add `math-physics` and `radiuss`.

**Comment by jbschroder** [comment]
Hi, I'm happy to connect XBraid to math-physics and radiuss, but I don't know how to do this.  Can you describe how to do this?  Do I change some kind of setting inside of Github? - Jacob

**Comment by hauten** [comment]
Thank you! It's super easy, see screen shot.
![manage topics](https://user-images.githubusercontent.com/31740953/59797537-c3d76880-9294-11e9-849e-48d8ea0631f7.png)

**Comment by jbschroder** [comment]
OK, I think that I added these two topics.  Let me know if it didn't work.
 - Jacob

**Comment by hauten** [comment]
Perfect, thank you @jbschroder
