### ISSUE TITLE
Splitting up large braid.c and util.c files

### ISSUE THREAD

**Issue by jbschroder** [XBraid/xbraid#4]
Here's my opinion about naming conventions...

I personally like separating user interface from internal interface.  User's include `.h` files and call functions, so they should only include the `braid.h` file and call functions that begin with `braid_`.  Because of this, we need `.h` files that begin with `_braid_` to put all other header information that users should not see.  However, the `.c` files really can have any names we like and implement any of the functions, either internal or external or both.  In other words, I'm not sure we need to name any of the `.c` files with prefixes `braid_` or `_braid_`.

I would still vote for putting user interface implementations in `.c` files that begin with `braid_` just to make them easy to find, but I am okay with also putting internal functions in these files when it makes sense (helper functions, for example; `braid.c` does this).  So, I would prefer `_braid_status.c` to be `braid_status.c`.  I don't think we need to name any of the `.c` files with `_braid_`.  So, I would be in favor of splitting and renaming the `_braid.c` and `_util.c` files into a number of `.c` files (that do not begin with underscore) that better reflect the code.  For example, `_braid.c` could be split into files such as

  distribution.c
  communication.c
  uvector.c
  step.c
  residual.c
  interp.c
  restrict.c
  refine.c
  space.c
  hierarchy.c
  ...

Maybe we shouldn't split it up quite so much?  Just some thoughts to ponder.

-Rob

**Comment by rfalgout** [comment]
This issue was addressed in pull request #39
