### ISSUE TITLE
Use of printf

### ISSUE THREAD

**Issue by jbschroder** [XBraid/xbraid#51]
@steffi7574 @rfalgout 
Hi Stefanie,

Rob and I were talking about the use of "printf" versus "_braid_printf", and we saw some printf statements in base.c related to 
" if (verbose_adj) "
then print some debug output.  And a few "printf" statements in tape.c 

Do you remember why we use printf, instead of _braid_printf here?  And could we replace them with _braid_printf?

Thanks!

Jacob

**Comment by steffi7574** [comment]
Hi Jacob,

they all can be replace by "_braid_printf". Sorry for that. I can do the change.

Stefanie

**Comment by steffi7574** [comment]
I just created a pull request.

**Comment by jbschroder** [comment]
@steffi7574 @rfalgout 
Thanks for putting this together Stefanie!  I just merged the pull request, so I'm going to close this ticket.

Cheers,

Jacob
