### ISSUE TITLE
Fixed-Point Test with FMG: First Iteration Residual is Non-Zero

### ISSUE THREAD

**Issue by jcc242** [XBraid/xbraid#57]
Per our discussion yesterday, I did a little bit of digging into why the first iteration's residual is not zero when doing the fixed point test with FMG. Here is what I found.

I started the simulation with just 1 MGRIT level as I typically do with my MGRIT-AMR. The initial sequential solve of this single MGRIT level tags some temporal intervals for refinement with SetRFactor. Refinement is performed and we begin a two-level scheme with a down cycle on the fine level (that is, level 0). I'll list the steps out so its clear:

1. Single level MGRIT, solved sequentially
2. Refinement occurs, now have 2 MGRIT levels
3. Down cycle on level 0, FRestrict is performed here, and during FRestrict the norm is calculated.
4. Up cycle on level 1
5. Up cycle on level 0. The exact solution for the fixed-point test is set here with a sequential solve of the fine time grid. Immediately afterwards the norm is written to the screen/output file. From what I can tell, the norm is not re-calculated after the exact solution is set and before being written out.

I'm not entirely certain what the solution here is. We detect that it is time to set the exact solution by checking `core.rstopped`, but `core.rstopped` isn't updated until some point after the down cycle in step 3 above.

**Comment by jbschroder** [comment]
Hi Joshua,   Thanks for looking into this.  It seems like step "5" should
go before step "3".  But with the steps you outline, your observed output
of a nonzero residual in step "3" makes sense, and it's only after step "5"
that you see a machine zero residual. - Jacob

**Comment by jcc242** [comment]
Dr. Schroder,

Do you have any thoughts on how to actually resolve this in the code? The data we use to detect it is time to apply the exact solution (rstopped) does not appear to be set until sometime after step 3. Can we recompute the residual somehow  after setting the exact solution?

Another approach is to maybe just set the residual to zero? This has precedent. When there is just one temporal level, after FCRelax the norm is set to identically zero: https://github.com/XBraid/xbraid/blob/9795117917958b27a12d43b85ef1c21f1519d87e/braid/drive.c#L487 
I am a little hesitant to hard-code something like that though.

Thanks,
Joshua

**Comment by jcc242** [comment]
From our discussion:

Checking `rstopped` is an optimization so we only apply the exact solution once. Since performing a fixed point test is a debugging step, we aren't concerned about optimization. Therefore we can apply the exact solution immediately after every refinement, and hence before FRestrict (and the norm calculation) on the fine temporal level.

I'll put together a patch and pull request for this in the next week.

**Comment by jcc242** [comment]
Fixed in PR #61, commit 82bf63e
