### ISSUE TITLE
Coupling of XBraid with an Eigen-based code

### ISSUE THREAD

**Issue by mmoelle1** [XBraid/xbraid#66]
Based on the example `ex-01-pp.cpp` I have developed a small test application where vectors are stored as dynamic Eigen vectors. `gsMatrix<T>` is an alias for Eigen::Matrix<T> in the code below.

Allocation of vectors is done in the `Init` method (and in `Clone`), e.g.,

```cpp
int Init(T             t,
         braid_Vector *u_ptr) override
  {
    gsMatrix<T>* u = new gsMatrix<T>(100, 1);
    u->setZero(100, 1);
    *u_ptr = (braid_Vector) u;
    return 0;
  }
```

I still have one problem with the correct implementation of `Free`.

```cpp
int Free(braid_Vector u)
  {
    gsMatrix<T>* _u = (gsMatrix<T>*) u;
    //_u->clear();
    delete _u;
    return 0;
  }
```

When I uncomment the `clear()` method then the vectors size is `(0,0)` and the next clone fails (trying to clone a vector of size `(0,0)`). Should the `Free` method really deallocate the vector and its content or only the pointer?

Any help is appreciated.

**Comment by jbschroder** [comment]
Hi Matthias,

The Free function should deallocate the vector.  While it is C (not C++),
you can take a look at ex-02.c, and see how the vector structure (object in
C++) contains a (double *) array of values.

The Free function then frees this (double *) chunk of memory, while clone
and init allocate memory for it.  Your C++ code should mirror that.

Hope this helps,

Jacob

**Comment by mmoelle1** [comment]
Hi Jacob,

it works! At the end it was a bug in my `Clone` function. Thanks for your help.

Matthias
