### ISSUE TITLE
example of using adaptive stepping solver along with xbraid

### ISSUE THREAD

**Issue by yizhang-yiz** [XBraid/xbraid#71]
In [this presentation](https://conferences.math.mtu.edu/wp-content/uploads/2020/06/PinT_2020_SUNDIALS_XBraid_Talk.pdf) it's mentioned that akrode's adaptive stepping integrator was used with xbraid. Is there an example to show how do this? Looks like all the examples so far are based on fixed time step.

**Comment by jbschroder** [comment]
@gardner48 Hi David, do you have any more information on ARKODE and XBraid?

**Comment by gardner48** [comment]
The example code from the presentation can be found [here](https://github.com/LLNL/sundials/tree/master/examples/arkode/CXX_xbraid), it's specifically `ark_heat2D_hypre_pfmg_xbraid.cpp`. There is also a version that does not use _hypre_ (`ark_heat2D_p_xbraid.cpp`) and a version that is serial in space (`ark_heat2D_xbraid.cpp`). To enable adaptivity in any of these you'll need to pass the `--x_refine` command line option.

**Comment by jbschroder** [comment]
Thanks David!

**Comment by yizhang-yiz** [comment]
Thanks a lot! @gardner48 @jbschroder

**Comment by gardner48** [comment]
@yizhang-yiz I'll also add that if you want to see how these examples differ from using ARKODE without XBraid each one has a corresponding serial in time version in `examples/arkode/CXX_parhyp`, `examples/arkode/CXX_parallel` and `examples/arkode/CXX_serial` respectively.

**Comment by yizhang-yiz** [comment]
@gardner48 thank you so much! I'll look into them.
