### ISSUE TITLE
different definitions of C and C++

### ISSUE THREAD

**Issue by parnet** [XBraid/xbraid#75]
Hey 
in the C++ interface of BraidStepStatus

the void SetTightFineTolx(**braid_Int** tight_fine_tolx) function has the datatype int while the c interface uses real

braid_StatusSetTightFineTolx(braid_Status status,  **braid_Real**   tight_fine_tolx );

is it correct? another difference is in class BraidCore the function GetCFactor seems to be restricted to only one level.

void GetCFactor(braid_Int *cfactor_ptr) { _braid_GetCFactor(core, **0,** cfactor_ptr); }

compare to

braid_Int _braid_GetCFactor(braid_Core   core, **braid_Int    level**, braid_Int   *cfactor_ptr);

hope this helps :) 
best regards parnet

**Comment by jbschroder** [comment]
Hi Arne,

Thanks for catching these!  I just pushed a commit that should remove these inconsistencies.  I didn't get rid of the existing GetCFactor() function, in case someone is using it.  So, I just added a new GetCFactor function with level and cfactor parameters.

Cheers,

Jacob
