### ISSUE TITLE
Braid always prints " wall time = 0.00000 " on latest revision

### ISSUE THREAD

**Issue by cadaverous-lives** [XBraid/xbraid#87]
After pulling from master, I noticed that the latest commits have caused braid to print 0.000 for the global wall time. This happens in serial and parallel. Not sure what is causing it, but I know @jbschroder was working on timing features recently, and this could easily slip past the regression tests, since they can't check for timing.

**Comment by jbschroder** [comment]
Yes...this was indeed the case.  I just pushed an update to Braid to fix this.  Let me know if the new push doesn't resolve it on your end.

**Comment by cadaverous-lives** [comment]
Seems like it's fixed! :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
