### ISSUE TITLE
Error compiling Cython file

### ISSUE THREAD

**Issue by wsheat** [XBraid/xbraid#95]
After successfully  compiling the source code , I follow the instruction in ex_01-setup.py trying to install module of ex1. When I run **python3 ex_01-setup.py install --prefix=$HOME/.local** in terminal. It will report an error like:
```
Error compiling Cython file:
    # Must increment smart pointer for app, or else Python will delete it 
    Py_INCREF(pyApp)

    # Initialize Braid
    braid_Init(comm.ob_mpi, comm.ob_mpi, tstart, tstop, ntime, 
               <braid_App> pyApp, my_step, my_init, my_clone, my_free, my_sum, 
                                  ^
ex_01.pyx:306:34: Cannot assign type 'int (braid_App, braid_Vector, braid_Vector, braid_Vector, braid_StepStatus) except? -1' to 'braid_PtFcnStep'
```
My Cython version is 3.0.0 , python  version is 3.11.6. By the way , I run the command in conda environment. I'm new to Cython, any suggustion would be appreciated !

**Comment by jbschroder** [comment]
Hi,

It seems that Cython introduced some backwards incompatible changes when
going from 0.29 to 3.0.  Python unfortunately does this sometimes.  So, at
this point, I'm not sure what got broken.  As a quick fix, you could try
reverting your Cython version to 0.29.

Thanks,

Jacob

**Comment by wsheat** [comment]
Thank you for your reply. It works!
